version: "3"

services:
  app:
    image: i-platziapp:latest
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: i-mongo:latest
